### ISSUE TITLE
Erreurs nombreuses / lors d'erreur de validation de token

### ISSUE THREAD

**Issue by rhanka** [matchID-project/deces-backend#321]
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (/deces-backend/node_modules/express/lib/response.js:776:10)
    at ServerResponse.send (/deces-backend/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/deces-backend/node_modules/express/lib/response.js:267:15)
    at /deces-backend/dist/server.js:100:32
    at Layer.handle_error (/deces-backend/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/deces-backend/node_modules/express/lib/router/index.js:321:13)
    at /deces-backend/node_modules/express/lib/router/index.js:284:7

**Comment by rhanka** [comment]
error is not appearing anymore
