### ISSUE TITLE
Errors raised in ScoreName when undefined

### ISSUE THREAD

**Issue by rhanka** [matchID-project/deces-backend#352]
More than 10k error a day : 
backend.error.stack:TypeError: Cannot read properties of undefined (reading 'toString')
    at scoreName (/deces-backend/dist/score.js:222:123)
    at new ScoreResult (/deces-backend/dist/score.js:665:33)
    at /deces-backend/dist/score.js:736:29
    at Array.map (<anonymous>)
    at scoreResults (/deces-backend/dist/score.js:734:10)
    at buildResult (/deces-backend/dist/models/result.js:39:30)
    at SearchController.<anonymous> (/deces-backend/dist/controllers/search.controller.js:135:62)
    at Generator.next (<anonymous>)
    at fulfilled (/deces-backend/dist/controllers/search.controller.js:14:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by rhanka** [comment]
in ts, seams to be on line 232

**Comment by rhanka** [comment]
Example of request to reproduce the error:
http://localhost:8083/search?advanced=true&ln=de+combarel+du+g&sex=M
