### ISSUE TITLE
Uncatched error in bulk api

### ISSUE THREAD

**Issue by rhanka** [matchID-project/deces-backend#383]

**Comment by rhanka** [comment]
The following error is uncatched:
`Error: Missing lock for job 660ebb34b62b9ec68c6986fd6f39acd18b96d53846c1550730cc057d3d0554ca-9. retryJob
    at Scripts.finishedErrors (/deces-backend/node_modules/bullmq/dist/cjs/classes/scripts.js:211:24)
    at Job.moveToFailed (/deces-backend/node_modules/bullmq/dist/cjs/classes/job.js:409:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleFailed (/deces-backend/node_modules/bullmq/dist/cjs/classes/worker.js:326:21)
    at async Worker.retryIfFailed (/deces-backend/node_modules/bullmq/dist/cjs/classes/worker.js:524:24)
`
it should be catched and wrapped with timestamp in the backend logger to allow time framed contextualized investigations.

**Comment by rhanka** [comment]
fully solved with #460
